// Curated popular neon font library (mirrors server neonDefaults). The admin can
// one-click merge any missing fonts into the live catalogue. The customer app
// loads these families in its index.html.

export const NEON_FONT_LIBRARY = [
  { key: 'pacifico', name: 'Pacifico', cssFamily: "'Pacifico', cursive", script: true },
  { key: 'dancing', name: 'Dancing', cssFamily: "'Dancing Script', cursive", script: true },
  { key: 'kaushan', name: 'Kaushan', cssFamily: "'Kaushan Script', cursive", script: true },
  { key: 'greatvibes', name: 'Great Vibes', cssFamily: "'Great Vibes', cursive", script: true },
  { key: 'sacramento', name: 'Sacramento', cssFamily: "'Sacramento', cursive", script: true },
  { key: 'satisfy', name: 'Satisfy', cssFamily: "'Satisfy', cursive", script: true },
  { key: 'cookie', name: 'Cookie', cssFamily: "'Cookie', cursive", script: true },
  { key: 'allura', name: 'Allura', cssFamily: "'Allura', cursive", script: true },
  { key: 'parisienne', name: 'Parisienne', cssFamily: "'Parisienne', cursive", script: true },
  { key: 'yellowtail', name: 'Yellowtail', cssFamily: "'Yellowtail', cursive", script: true },
  { key: 'lobster', name: 'Lobster', cssFamily: "'Lobster', cursive", script: true },
  { key: 'courgette', name: 'Courgette', cssFamily: "'Courgette', cursive", script: true },
  { key: 'caveat', name: 'Caveat', cssFamily: "'Caveat', cursive", script: true },
  { key: 'marker', name: 'Marker', cssFamily: "'Permanent Marker', cursive", script: true },
  { key: 'shadows', name: 'Handwritten', cssFamily: "'Shadows Into Light', cursive", script: true },
  { key: 'neonderthaw', name: 'Neonderthaw', cssFamily: "'Neonderthaw', cursive", script: true },
  { key: 'tiltneon', name: 'Tilt Neon', cssFamily: "'Tilt Neon', sans-serif", script: false },
  { key: 'monoton', name: 'Monoton', cssFamily: "'Monoton', cursive", script: false },
  { key: 'bungee', name: 'Bungee', cssFamily: "'Bungee', cursive", script: false },
  { key: 'audiowide', name: 'Audiowide', cssFamily: "'Audiowide', sans-serif", script: false },
  { key: 'righteous', name: 'Righteous', cssFamily: "'Righteous', sans-serif", script: false },
  { key: 'orbitron', name: 'Orbitron', cssFamily: "'Orbitron', sans-serif", script: false },
  { key: 'bebas', name: 'Bebas Neue', cssFamily: "'Bebas Neue', sans-serif", script: false },
  { key: 'anton', name: 'Anton', cssFamily: "'Anton', sans-serif", script: false },
  // Extended catalogue.
  { key: 'playfair', name: 'Playfair Display', cssFamily: "'Playfair Display', serif", script: false },
  { key: 'cinzel', name: 'Cinzel', cssFamily: "'Cinzel', serif", script: false },
  { key: 'cormorant', name: 'Cormorant', cssFamily: "'Cormorant Garamond', serif", script: false },
  { key: 'abril', name: 'Abril Fatface', cssFamily: "'Abril Fatface', serif", script: false },
  { key: 'alfaslab', name: 'Alfa Slab One', cssFamily: "'Alfa Slab One', serif", script: false },
  { key: 'lobstertwo', name: 'Lobster Two', cssFamily: "'Lobster Two', cursive", script: true },
  { key: 'pattaya', name: 'Pattaya', cssFamily: "'Pattaya', sans-serif", script: true },
  { key: 'marck', name: 'Marck Script', cssFamily: "'Marck Script', cursive", script: true },
  { key: 'rocksalt', name: 'Rock Salt', cssFamily: "'Rock Salt', cursive", script: true },
  { key: 'amatic', name: 'Amatic SC', cssFamily: "'Amatic SC', cursive", script: true },
  { key: 'tangerine', name: 'Tangerine', cssFamily: "'Tangerine', cursive", script: true },
  { key: 'pinyon', name: 'Pinyon Script', cssFamily: "'Pinyon Script', cursive", script: true },
  { key: 'alexbrush', name: 'Alex Brush', cssFamily: "'Alex Brush', cursive", script: true },
  { key: 'kalam', name: 'Kalam', cssFamily: "'Kalam', cursive", script: true },
  { key: 'damion', name: 'Damion', cssFamily: "'Damion', cursive", script: true },
  { key: 'rye', name: 'Rye', cssFamily: "'Rye', cursive", script: false },
  { key: 'fredericka', name: 'Fredericka', cssFamily: "'Fredericka the Great', cursive", script: true },
  { key: 'bungeeshade', name: 'Bungee Shade', cssFamily: "'Bungee Shade', cursive", script: false },
  { key: 'poiret', name: 'Poiret One', cssFamily: "'Poiret One', sans-serif", script: false },
  { key: 'sail', name: 'Sail', cssFamily: "'Sail', cursive", script: false },
];

export default NEON_FONT_LIBRARY;
